# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7461dc7334fdd05804da7e88c61fbbc31ed4d84312cbb52e512544339bd1382260f648093fcb388c33278dfeb5f696bc3681647488421b884d776ea2bf92b42

test:
  secret_key_base: 87fda792ed0507a19f64c02ecd50ceff9b52fe13e3c6e563c6fa0879c6899509dd24394523fbd3b40b68c463a931342ba042c8d902b80d294ce05c413dcdf106

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
